name: qattah_project
description: A new Flutter project.

version: 1.0.0+1

environment:
    sdk: '>=2.18.6 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    firebase_core: ^2.7.0
    smooth_page_indicator: ^1.0.1
    dotted_border: ^2.0.0+3
    firebase_auth: ^4.2.9
    lottie: ^2.2.0
    image_picker: ^0.8.6+4
    theme_mode_builder:
    cloud_firestore: ^4.4.4

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    dart_code_metrics: ^5.6.0
    dart_code_metrics_presets: ^1.3.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/

    fonts:
        - family: AllGenders
          fonts:
              - asset: assets/fonts/AllGendersRegular.otf
              - asset: assets/fonts/AllGendersBold.otf
                weight: 900
              - asset: assets/fonts/AllGendersLight.otf
                weight: 100
