// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVQchIfmZNNI9ZmIGHdhZ_Z6iJq5Cu_7I',
    appId: '1:156077316211:web:6a4b2795ec81b3afdb3206',
    messagingSenderId: '156077316211',
    projectId: 'qatah-app',
    authDomain: 'qatah-app.firebaseapp.com',
    storageBucket: 'qatah-app.appspot.com',
    measurementId: 'G-HPTM98HMCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCOceXjAixt3OpIVKG1nByn2ftmAf5QoY',
    appId: '1:156077316211:android:00c96615d227ea74db3206',
    messagingSenderId: '156077316211',
    projectId: 'qatah-app',
    storageBucket: 'qatah-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU2-laeHMM16L3qWk7Xu1N8ZgRybbu4tA',
    appId: '1:156077316211:ios:32db153549482bb3db3206',
    messagingSenderId: '156077316211',
    projectId: 'qatah-app',
    storageBucket: 'qatah-app.appspot.com',
    iosClientId: '156077316211-sc8llpbd6vr1lc65eo625rv9tnsre3gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.qattahProject',
  );
}
